trigger:
  batch: true
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - azure-pipelines/release.yml
    - azure-pipelines/vs-insertion.yml
#schedules:
#- cron: "0 3 * * *" # Daily @ 8 PM PST
#  displayName: Daily vs-insertion
#  branches:
#    include:
#    - microbuild
pr: none

parameters:
- name: SignTypeSelection
  displayName: Sign type
  type: string
  default: Test
  values: [ 'Test', 'Real' ]
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true
- name: EnableCompliance
  displayName: Run Compliance Tools
  type: boolean
  default: true
- name: EnableAPIScan
  displayName: Include APIScan with Compliance tools
  type: boolean
  default: true

stages:

- stage: Build
  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
    NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
    MicroBuild_DoNotStrongNameSign: true
    SignTypeSelection: ${{ parameters.SignTypeSelection }}
    Packaging.EnableSBOMSigning: false
    Codeql.Enabled: true

  jobs:
  - template: build.yml
    parameters:
      EnableCompliance: ${{ parameters.EnableCompliance }}
      EnableAPIScan: ${{ parameters.EnableAPIScan }}
      windowsPool: VSEngSS-MicroBuild2022-1ES
      RunTests: ${{ parameters.RunTests }}

- template: prepare-insertion-stages.yml

- stage: azure_public_vssdk_feed
  displayName: azure-public/vssdk feed
  condition: and(succeeded(), eq(dependencies.Build.outputs['Windows.SetPipelineVariables.SignType'], 'Real'))
  jobs:
  - deployment: push
    pool:
      vmImage: ubuntu-latest
    environment: No-Approval
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: deployables-Windows
            displayName: Download deployables-Windows artifact
          - task: NuGetToolInstaller@1
            displayName: Use NuGet 5.x
            inputs:
              versionSpec: 5.x
          - task: NuGetCommand@2
            displayName: NuGet push
            inputs:
              command: push
              packagesToPush: $(Pipeline.Workspace)/deployables-Windows/NuGet/*.nupkg
              nuGetFeedType: external
              publishFeedCredentials: azure-public/vssdk
              allowPackageConflicts: true
            continueOnError: true # until "skip on conflict" is offered as a task input.
